const database = {
    products: [{
        "id": 1,
        "name": "Cocoa Powder - Natural",
        "price": 8.68,
        "productTypeId": 5
    }, {
        "id": 2,
        "name": "Macaroons - Two Bite Choc",
        "price": 12.59,
        "productTypeId": 3
    }, {
        "id": 3,
        "name": "Beef Wellington",
        "price": 9.04,
        "productTypeId": 4
    }, {
        "id": 4,
        "name": "Coffee - Cafe Moreno",
        "price": 7.09,
        "productTypeId": 3
    }, {
        "id": 5,
        "name": "Thyme - Lemon, Fresh",
        "price": 19.26,
        "productTypeId": 3
    }, {
        "id": 6,
        "name": "Wine - Chenin Blanc K.w.v.",
        "price": 7.97,
        "productTypeId": 3
    }, {
        "id": 7,
        "name": "Crab Meat Claw Pasteurise",
        "price": 15.11,
        "productTypeId": 2
    }, {
        "id": 8,
        "name": "Bread - Raisin Walnut Pull",
        "price": 8.86,
        "productTypeId": 3
    }, {
        "id": 9,
        "name": "Pastry - Chocolate Chip Muffin",
        "price": 10.82,
        "productTypeId": 4
    }, {
        "id": 10,
        "name": "Bouq All Italian - Primerba",
        "price": 6.04,
        "productTypeId": 4
    }, {
        "id": 11,
        "name": "Sugar - White Packet",
        "price": 8.14,
        "productTypeId": 3
    }, {
        "id": 12,
        "name": "Cheese - Cream Cheese",
        "price": 10.77,
        "productTypeId": 4
    }, {
        "id": 13,
        "name": "Pastry - Lemon Danish - Mini",
        "price": 13.39,
        "productTypeId": 4
    }, {
        "id": 14,
        "name": "Pumpkin",
        "price": 9.57,
        "productTypeId": 2
    }, {
        "id": 15,
        "name": "Nut - Walnut, Pieces",
        "price": 17.8,
        "productTypeId": 2
    }, {
        "id": 16,
        "name": "Petit Baguette",
        "price": 7.55,
        "productTypeId": 2
    }, {
        "id": 17,
        "name": "Potatoes - Idaho 100 Count",
        "price": 6.82,
        "productTypeId": 3
    }, {
        "id": 18,
        "name": "Crawfish",
        "price": 5.54,
        "productTypeId": 5
    }, {
        "id": 19,
        "name": "Beer - True North Strong Ale",
        "price": 10.71,
        "productTypeId": 3
    }, {
        "id": 20,
        "name": "Juice - V8, Tomato",
        "price": 18.72,
        "productTypeId": 4
    }],
    orders: [{
        "id": 1,
        "productId": 18,
        "employeeId": 5,
        "timestamp": 1068578470
    }, {
        "id": 2,
        "productId": 17,
        "employeeId": 2,
        "timestamp": 1568299435
    }, {
        "id": 3,
        "productId": 14,
        "employeeId": 1,
        "timestamp": 1180406577
    }, {
        "id": 4,
        "productId": 15,
        "employeeId": 5,
        "timestamp": 1353639905
    }, {
        "id": 5,
        "productId": 20,
        "employeeId": 3,
        "timestamp": 1540188871
    }, {
        "id": 6,
        "productId": 14,
        "employeeId": 4,
        "timestamp": 1270669436
    }, {
        "id": 7,
        "productId": 15,
        "employeeId": 5,
        "timestamp": 1366987025
    }, {
        "id": 8,
        "productId": 17,
        "employeeId": 4,
        "timestamp": 1217124539
    }, {
        "id": 9,
        "productId": 4,
        "employeeId": 2,
        "timestamp": 1566260897
    }, {
        "id": 10,
        "productId": 7,
        "employeeId": 3,
        "timestamp": 1092295306
    }, {
        "id": 11,
        "productId": 14,
        "employeeId": 3,
        "timestamp": 1370361567
    }, {
        "id": 12,
        "productId": 15,
        "employeeId": 5,
        "timestamp": 1394011023
    }, {
        "id": 13,
        "productId": 2,
        "employeeId": 3,
        "timestamp": 1230954091
    }, {
        "id": 14,
        "productId": 1,
        "employeeId": 1,
        "timestamp": 1023963203
    }, {
        "id": 15,
        "productId": 11,
        "employeeId": 1,
        "timestamp": 1536387202
    }, {
        "id": 16,
        "productId": 1,
        "employeeId": 5,
        "timestamp": 1535019580
    }, {
        "id": 17,
        "productId": 13,
        "employeeId": 1,
        "timestamp": 1185637203
    }, {
        "id": 18,
        "productId": 12,
        "employeeId": 5,
        "timestamp": 1251044007
    }, {
        "id": 19,
        "productId": 15,
        "employeeId": 1,
        "timestamp": 1561035040
    }, {
        "id": 20,
        "productId": 19,
        "employeeId": 2,
        "timestamp": 1612850561
    }, {
        "id": 21,
        "productId": 13,
        "employeeId": 1,
        "timestamp": 1033598467
    }, {
        "id": 22,
        "productId": 9,
        "employeeId": 5,
        "timestamp": 1361256978
    }, {
        "id": 23,
        "productId": 10,
        "employeeId": 1,
        "timestamp": 1489462434
    }, {
        "id": 24,
        "productId": 12,
        "employeeId": 1,
        "timestamp": 1503941707
    }, {
        "id": 25,
        "productId": 16,
        "employeeId": 2,
        "timestamp": 1515060640
    }, {
        "id": 26,
        "productId": 1,
        "employeeId": 4,
        "timestamp": 1265675393
    }, {
        "id": 27,
        "productId": 11,
        "employeeId": 5,
        "timestamp": 1082406362
    }, {
        "id": 28,
        "productId": 12,
        "employeeId": 5,
        "timestamp": 1127914121
    }, {
        "id": 29,
        "productId": 16,
        "employeeId": 2,
        "timestamp": 1377041444
    }, {
        "id": 30,
        "productId": 5,
        "employeeId": 5,
        "timestamp": 1623705019
    }, {
        "id": 31,
        "productId": 18,
        "employeeId": 2,
        "timestamp": 1439663805
    }, {
        "id": 32,
        "productId": 20,
        "employeeId": 5,
        "timestamp": 1380520533
    }, {
        "id": 33,
        "productId": 17,
        "employeeId": 2,
        "timestamp": 1549996324
    }, {
        "id": 34,
        "productId": 18,
        "employeeId": 4,
        "timestamp": 1524287817
    }, {
        "id": 35,
        "productId": 13,
        "employeeId": 1,
        "timestamp": 1614293048
    }, {
        "id": 36,
        "productId": 2,
        "employeeId": 5,
        "timestamp": 1156292088
    }, {
        "id": 37,
        "productId": 10,
        "employeeId": 5,
        "timestamp": 1609088239
    }, {
        "id": 38,
        "productId": 2,
        "employeeId": 2,
        "timestamp": 1526574185
    }, {
        "id": 39,
        "productId": 15,
        "employeeId": 5,
        "timestamp": 1050913339
    }, {
        "id": 40,
        "productId": 3,
        "employeeId": 5,
        "timestamp": 1195084067
    }, {
        "id": 41,
        "productId": 20,
        "employeeId": 1,
        "timestamp": 1462678623
    }, {
        "id": 42,
        "productId": 20,
        "employeeId": 3,
        "timestamp": 1249312633
    }, {
        "id": 43,
        "productId": 7,
        "employeeId": 5,
        "timestamp": 1466527920
    }, {
        "id": 44,
        "productId": 19,
        "employeeId": 1,
        "timestamp": 1585044446
    }, {
        "id": 45,
        "productId": 7,
        "employeeId": 4,
        "timestamp": 1448649015
    }, {
        "id": 46,
        "productId": 1,
        "employeeId": 5,
        "timestamp": 1193198643
    }, {
        "id": 47,
        "productId": 15,
        "employeeId": 1,
        "timestamp": 1180901260
    }, {
        "id": 48,
        "productId": 14,
        "employeeId": 3,
        "timestamp": 1055435407
    }, {
        "id": 49,
        "productId": 12,
        "employeeId": 5,
        "timestamp": 1166565841
    }, {
        "id": 50,
        "productId": 7,
        "employeeId": 2,
        "timestamp": 1371843344
    }],
    employees: [{
        "id": 1,
        "first_name": "Willis",
        "last_name": "Finessy",
        "age": 21
    }, {
        "id": 2,
        "first_name": "Lenard",
        "last_name": "Quilliam",
        "age": 19
    }, {
        "id": 3,
        "first_name": "Valli",
        "last_name": "Yeld",
        "age": 21
    }, {
        "id": 4,
        "first_name": "Ruperta",
        "last_name": "Bachelor",
        "age": 23
    }, {
        "id": 5,
        "first_name": "Allan",
        "last_name": "Raigatt",
        "age": 31
    }],
    productTypes: [
        { "id": 1, "type": "Produce" },
        { "id": 2, "type": "Sundries" },
        { "id": 3, "type": "Dairy" },
        { "id": 4, "type": "Meat" },
        { "id": 5, "type": "Snacks" }
    ]
}

export const getOrders = () => database.orders.map(order => ({...order}))
export const getEmployees = () => database.employees.map(employee => ({...employee}))
export const getProducts = () => database.products.map(product => ({...product}))
export const getProductTypes = () => database.productTypes.map(productType => ({...productType}))